# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!


pod 'ReactiveCocoa'
pod 'AVOSCloud', '~> 3.1'

target 'friend' do

end

target 'friendTests' do

end

